# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zz13J7DGH8oOigICLSX3_-z1PO36NGa-
"""

# ===========================================================
# CUSTOMER RFM + OFFER + BILLING DASHBOARD (FULL PROGRAM)
# ===========================================================

import streamlit as st
import pandas as pd
from datetime import datetime
from sklearn.cluster import KMeans

st.set_page_config(page_title="Customer RFM + Offer + Billing", layout="wide")

st.title("🛍️ Customer RFM + Offer + Billing Dashboard (India)")


# -----------------------------------------------------------
# DEFAULT OFFER %
# User can edit these during runtime
# -----------------------------------------------------------
if "offer_dict" not in st.session_state:
    st.session_state.offer_dict = {
        "Big Offer": 30,
        "Medium Offer": 20,
        "Small Offer": 10,
        "No Offer": 0
    }


# -----------------------------------------------------------
# Sidebar: Offer editing functionality
# -----------------------------------------------------------
st.sidebar.header("✏ Edit Offer Percentage (%)")

for key in st.session_state.offer_dict.keys():
    st.session_state.offer_dict[key] = st.sidebar.number_input(
        f"{key} (%)",
        min_value=0,
        max_value=100,
        step=1,
        value=st.session_state.offer_dict[key]
    )


# -----------------------------------------------------------
# File Upload
# -----------------------------------------------------------
uploaded_file = st.file_uploader("📤 Upload your CSV customer dataset", type=["csv"])
if uploaded_file is None:
    st.info("➡ Please upload dataset to continue...")
    st.stop()


df = pd.read_csv(uploaded_file)

required_cols = ["CustomerID", "InvoiceNo", "InvoiceDate", "Quantity", "UnitPrice", "Description"]
for col in required_cols:
    if col not in df.columns:
        st.error(f"❌ Missing column: {col}")
        st.stop()

df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
df["TotalAmount"] = df["Quantity"] * df["UnitPrice"]


# -----------------------------------------------------------
# RFM Calculation
# -----------------------------------------------------------
snapshot_date = df["InvoiceDate"].max() + pd.Timedelta(days=1)

rfm = df.groupby("CustomerID").agg({
    "InvoiceDate": lambda x: (snapshot_date - x.max()).days,
    "InvoiceNo": "nunique",
    "TotalAmount": "sum"
}).reset_index()

rfm.columns = ["CustomerID", "Recency", "Frequency", "Monetary"]


# -----------------------------------------------------------
# KMeans Segmentation using Frequency (to give offers)
# -----------------------------------------------------------
kmeans = KMeans(n_clusters=4, random_state=42)
rfm["Cluster"] = kmeans.fit_predict(rfm[["Frequency"]])

rfm["Offer Category"] = rfm["Cluster"].map({
    0: "Small Offer",
    1: "Medium Offer",
    2: "Big Offer",
    3: "No Offer"
})


# -----------------------------------------------------------
# Merge Offer %
# -----------------------------------------------------------
rfm["Discount %"] = rfm["Offer Category"].map(st.session_state.offer_dict)

st.subheader("📊 Customer RFM + Offer Table")
st.dataframe(rfm, use_container_width=True)


# -----------------------------------------------------------
# BILLING SYSTEM
# -----------------------------------------------------------
st.subheader("🧾 Billing System")

cid = st.text_input("Enter Customer ID for Billing")

if cid:
    if not cid.isnumeric() or int(cid) not in rfm["CustomerID"].values:
        st.error("❌ Customer not found")
    else:
        cid = int(cid)

        st.success("✅ Customer Found!")

        customer_data = df[df["CustomerID"] == cid].copy()
        customer_rfm = rfm[rfm["CustomerID"] == cid].iloc[0]

        # Show product summary
        product_summary = customer_data.groupby("Description").agg({"Quantity": "sum"}).reset_index()

        st.write("🛒 Product Purchase Summary")
        st.dataframe(product_summary, use_container_width=True)

        st.write(f"""
        **🎉 Congratulations! You got {customer_rfm['Offer Category']} ({customer_rfm['Discount %']}% OFF)**  
        - Frequency of Buying: **{customer_rfm['Frequency']} times**
        - Last Purchase was **{customer_rfm['Recency']} days ago**
        """)

        # Billing Calculation
        total_bill = customer_data["TotalAmount"].sum()

        discount_rs = (total_bill * int(customer_rfm["Discount %"])) // 100  # only integer rupees
        final_bill = total_bill - discount_rs

        st.markdown("---")
        st.subheader("💰 Final Billing Summary (INR)")

        col1, col2, col3 = st.columns(3)
        col1.metric("Total Amount", f"₹ {int(total_bill)}")
        col2.metric("Discount Applied", f"₹ {int(discount_rs)}")
        col3.metric("Final Amount", f"₹ {int(final_bill)}")

        st.success("✅ Billing Completed!")


