# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zz13J7DGH8oOigICLSX3_-z1PO36NGa-
"""
# ==============================================================
# CUSTOMER RFM + OFFER + BILLING DASHBOARD
# ==============================================================

import streamlit as st
import pandas as pd
import numpy as np
from datetime import datetime
from sklearn.cluster import KMeans
import plotly.express as px

# --------------------------------------------------------------
# ✅ Streamlit settings
# --------------------------------------------------------------
st.set_page_config(page_title="Customer RFM + Offer + Billing", layout="wide")
st.title("🛍️ Customer RFM + Offers + Billing (India)")

# --------------------------------------------------------------
# ✅ Sidebar Discount Edit (User Controlled)
# --------------------------------------------------------------
st.sidebar.subheader("✏️ Edit Discount Percentage")

small_discount = st.sidebar.number_input("Small Discount % (2 products)", min_value=0, max_value=100, value=5)
medium_discount = st.sidebar.number_input("Medium Discount % (3 products)", min_value=0, max_value=100, value=10)
big_discount = st.sidebar.number_input("Big Discount % (5+ products)", min_value=0, max_value=100, value=20)

# --------------------------------------------------------------
# ✅ File Upload Section
# --------------------------------------------------------------
uploaded_file = st.file_uploader("📂 Upload your Excel/CSV file", type=["xlsx", "csv"])

if uploaded_file:
    # Auto-read file
    if uploaded_file.name.endswith(".csv"):
        df = pd.read_csv(uploaded_file)
    else:
        df = pd.read_excel(uploaded_file)

    st.success("✅ File uploaded successfully!")

    # Auto column mapping
    df.columns = [c.lower() for c in df.columns]

    column_map = {
        "invoice": next((c for c in df.columns if "invoice" in c), None),
        "product": next((c for c in df.columns if "desc" in c or "product" in c), None),
        "price": next((c for c in df.columns if "price" in c), None),
        "customerid": next((c for c in df.columns if "customer" in c or "cust" in c), None),
        "quantity": next((c for c in df.columns if "qty" in c or "quantity" in c), None),
        "invoicedate": next((c for c in df.columns if "date" in c), None),
    }

    # Validate columns
    missing = [k for k, v in column_map.items() if v is None]
    if missing:
        st.error(f"❌ Missing Required Columns: {', '.join(missing)}")
        st.stop()

    # Rename DF to standard format
    df = df.rename(columns={
        column_map["invoice"]: "Invoice",
        column_map["product"]: "Product",
        column_map["price"]: "Price",
        column_map["customerid"]: "CustomerID",
        column_map["quantity"]: "Quantity",
        column_map["invoicedate"]: "InvoiceDate"
    })

    # Ensure data types
    df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"], errors="coerce")
    df["Price"] = pd.to_numeric(df["Price"], errors="coerce").fillna(0)
    df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce").fillna(0)

    # Create Amount column
    df["Amount"] = df["Quantity"] * df["Price"]

    # Remove rows with missing required fields (prevent NaN issues)
    df.dropna(subset=["CustomerID", "Product", "Amount"], inplace=True)

    # ----------------------------------------------------------
    # ✅ RFM Calculation
    # ----------------------------------------------------------
    max_date = df["InvoiceDate"].max()

    rfm = df.groupby("CustomerID").agg({
        "InvoiceDate": lambda x: (max_date - x.max()).days,  # Recency
        "Invoice": "nunique",  # Frequency
        "Amount": "sum"  # Monetary
    }).reset_index()

    rfm.columns = ["CustomerID", "Recency", "Frequency", "Monetary"]

    # KMeans without NaN values
    rfm_clean = rfm[["Recency", "Frequency", "Monetary"]].fillna(0)

    kmeans = KMeans(n_clusters=4, random_state=42)
    rfm["Cluster"] = kmeans.fit_predict(rfm_clean)

    # ----------------------------------------------------------
    # ✅ RFM Graphs
    # ----------------------------------------------------------
    st.subheader("📊 RFM Clustering")

    fig1 = px.scatter(rfm, x="Recency", y="Monetary", color="Cluster", title="Recency vs Monetary")
    st.plotly_chart(fig1, use_container_width=True)

    fig2 = px.bar(rfm, x="Cluster", y="CustomerID", title="Customer Count in Each Cluster", color="Cluster")
    st.plotly_chart(fig2, use_container_width=True)
    

    # ----------------------------------------------------------
    # ✅ Customer ID Input for Billing
    # ----------------------------------------------------------
    st.subheader("💳 Find Customer Purchase Details")
    customer_input = st.text_input("Enter Customer ID")

    if customer_input:
        try:
            customer_input = int(customer_input)
        except:
            st.error("❌ CustomerID must be numeric")
            st.stop()

        cust_df = df[df["CustomerID"] == customer_input]

        if cust_df.empty:
            st.error("❌ Customer not found")
            st.stop()

        cust_summary = cust_df.groupby(["Product"]).agg({
            "Quantity": "sum",
            "Amount": "sum",
            "InvoiceDate": lambda x: ", ".join(x.dt.strftime('%Y-%m-%d').unique())
        }).reset_index()

        # Determine offer type
        freq = cust_summary.shape[0]

        if freq >= 5:
            offer = "Big Discount"
            discount_percent = big_discount
        elif freq >= 3:
            offer = "Medium Discount"
            discount_percent = medium_discount
        elif freq >= 2:
            offer = "Small Discount"
            discount_percent = small_discount
        else:
            offer = "No Discount"
            discount_percent = 0

        # Apply discount (only integer rupees)
        cust_summary["Discount_Rs"] = (cust_summary["Amount"] * discount_percent / 100).astype(int)
        cust_summary["FinalAmount"] = cust_summary["Amount"] - cust_summary["Discount_Rs"]

        st.subheader("🧾 Product-wise Billing Table")
        st.dataframe(cust_summary)

        total = cust_summary["FinalAmount"].sum()

        st.subheader("📌 Billing Summary")
        st.write(f"**Total Products:** {freq}")
        st.write(f"**Offer Type:** {offer}")
        st.write(f"**Discount Applied:** {discount_percent}%")
        st.write(f"**Final Bill Amount:** ₹{total}")

