# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zz13J7DGH8oOigICLSX3_-z1PO36NGa-
"""


  # app.py
import streamlit as st
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import plotly.express as px

st.set_page_config(page_title="Customer RFM + Billing (India)", layout="wide")
st.title("🛍️ Customer RFM + Indian Billing Dashboard")

# -------------------------
# Helpers
# -------------------------
def find_col(df, candidates):
    for c in candidates:
        if c in df.columns:
            return c
    lower_cols = {col.lower(): col for col in df.columns}
    for c in candidates:
        if c.lower() in lower_cols:
            return lower_cols[c.lower()]
    return None


# -------------------------
# Sidebar Settings
# -------------------------
st.sidebar.header("⚙️ Settings")
big_discount = st.sidebar.number_input("Big Discount % (freq > 5)", min_value=0, max_value=100, value=20, step=1)
medium_discount = st.sidebar.number_input("Medium Discount % (freq > 3)", min_value=0, max_value=100, value=10, step=1)
small_discount = st.sidebar.number_input("Small Discount % (freq > 2)", min_value=0, max_value=100, value=5, step=1)

n_clusters = st.sidebar.slider("K (clusters for KMeans)", min_value=2, max_value=8, value=4)
show_cluster_table = st.sidebar.checkbox("Show cluster summary table", value=False)

# -------------------------
# 1) File upload
# -------------------------
st.header("1️⃣ Upload sales/transactions file (CSV or Excel)")
uploaded_file = st.file_uploader("Upload CSV / XLSX file", type=["csv", "xlsx"])

if uploaded_file:

    if uploaded_file.name.lower().endswith(".csv"):
        df = pd.read_csv(uploaded_file, dtype=str)
    else:
        df = pd.read_excel(uploaded_file, dtype=str)

    df.columns = [c.strip() for c in df.columns]

    product_col = find_col(df, ["Product", "Description", "Item", "Product Name"])
    customer_col = find_col(df, ["Customer ID", "CustomerID", "customer_id", "CID"])
    price_col = find_col(df, ["Price", "UnitPrice", "Unit Price", "Amount", "rate"])
    qty_col = find_col(df, ["Quantity", "Qty", "QTY", "Units"])
    invoice_date_col = find_col(df, ["InvoiceDate", "Invoice Date", "Date", "TransactionDate"])

    missing = []
    if not product_col: missing.append("Product/Description")
    if not customer_col: missing.append("Customer ID")
    if not price_col: missing.append("Price")
    if missing:
        st.error(f"Required column(s) missing: {', '.join(missing)}")
        st.stop()

    df["Product"] = df[product_col].astype(str)
    df["CustomerRaw"] = df[customer_col].astype(str).str.strip()

    # ✅ Force CustomerID as integer only
    try:
        df["CustomerID"] = pd.to_numeric(df["CustomerRaw"], errors='raise').astype(int)
    except:
        st.error("❌ Customer ID column contains non-integer values. Convert to integer in Excel and upload again.")
        st.stop()

    df["Price"] = pd.to_numeric(df[price_col], errors="coerce").fillna(0.0)
    df["Quantity"] = pd.to_numeric(df[qty_col], errors="coerce").fillna(1).astype(int) if qty_col else 1

    if invoice_date_col:
        df["InvoiceDate"] = pd.to_datetime(df[invoice_date_col], errors="coerce")
    else:
        df["InvoiceDate"] = pd.NaT

    df["TotalAmount"] = (df["Price"] * df["Quantity"]).round(2)

    st.success("✅ File loaded successfully.")
    st.subheader("Preview")
    st.dataframe(df.head())

    # -------------------------
    # RFM Calculation
    # -------------------------
    st.header("2️⃣ RFM Calculation & Visuals")

    if df["InvoiceDate"].notna().any():
        snapshot_date = df["InvoiceDate"].max() + pd.Timedelta(days=1)
        rfm = df.groupby("CustomerID").agg({
            "InvoiceDate": lambda x: (snapshot_date - x.max()).days,
            "Product": "count",
            "TotalAmount": "sum"
        }).reset_index().rename(columns={
            "InvoiceDate": "Recency",
            "Product": "Frequency",
            "TotalAmount": "Monetary"
        })
    else:
        rfm = df.groupby("CustomerID").agg({
            "Product": "count",
            "TotalAmount": "sum"
        }).reset_index().rename(columns={
            "Product": "Frequency",
            "TotalAmount": "Monetary"
        })
        rfm["Recency"] = np.nan

    rfm_for_clust = rfm.copy()
    rfm_for_clust["Recency"] = rfm_for_clust["Recency"].fillna(rfm_for_clust["Recency"].median())

    rfm_for_clust["Recency_log"] = np.log1p(rfm_for_clust["Recency"])
    rfm_for_clust["Frequency_log"] = np.log1p(rfm_for_clust["Frequency"])
    rfm_for_clust["Monetary_log"] = np.log1p(rfm_for_clust["Monetary"])

    scaler = StandardScaler()
    X = scaler.fit_transform(rfm_for_clust[["Recency_log", "Frequency_log", "Monetary_log"]])

    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    rfm_for_clust["Cluster"] = kmeans.fit_predict(X)

    rfm = rfm.merge(rfm_for_clust[["CustomerID", "Cluster"]], on="CustomerID", how="left")

    if show_cluster_table:
        st.subheader("Cluster Summary")
        st.dataframe(rfm.groupby("Cluster").mean().round(2))

    st.subheader("🟣 3D RFM Scatter")
    fig = px.scatter_3d(rfm, x="Recency", y="Frequency", z="Monetary", color="Cluster")
    st.plotly_chart(fig, use_container_width=True)

    # -------------------------
    # Customer Lookup & Billing
    # -------------------------
    st.header("3️⃣ Customer Lookup → Billing (₹ integer only)")

    sample_ids = rfm["CustomerID"].unique()[:20].tolist()
    st.write("Sample Customer IDs:", sample_ids)

    cust_input = st.text_input("Enter Customer ID (integer only)")

    if cust_input:

        # ✅ Only integer accepted
        if not cust_input.isdigit():
            st.error("❌ Customer ID should be an INTEGER like: 101, 4502, etc.")
            st.stop()

        cust_key = int(cust_input)

        cust_tx = df[df["CustomerID"] == cust_key]

        if cust_tx.empty:
            st.error("Customer ID not found.")
        else:
            st.success(f"Found {len(cust_tx)} rows for Customer ID {cust_key}")

            st.subheader("🛒 Purchased Products")
            st.dataframe(cust_tx[["Product", "Quantity", "Price", "InvoiceDate"]])

            freq_table = cust_tx.groupby("Product").agg({
                "Quantity": "sum",
                "InvoiceDate": lambda x: sorted(list(pd.to_datetime(x.dropna().unique())))
            }).reset_index().rename(columns={"Quantity": "Frequency"})

            freq_table["Bought Dates"] = freq_table["InvoiceDate"].apply(
                lambda dates: [pd.to_datetime(d).strftime("%Y-%m-%d") for d in dates]
            )
            freq_table = freq_table.drop(columns=["InvoiceDate"])

            # ✅ Updated offer logic
            def offer_label(freq):
                if freq > 5:
                    return f"🟢 Big Discount ({big_discount}%)"
                elif freq > 3:
                    return f"🟡 Medium Discount ({medium_discount}%)"
                elif freq > 2:
                    return f"🟠 Small Discount ({small_discount}%)"
                else:
                    return "🔴 No Offer (Watch)"

            freq_table["Offer"] = freq_table["Frequency"].apply(offer_label)

            invoice_rows = []
            for _, r in freq_table.iterrows():
                prod = r["Product"]
                qty = int(r["Frequency"])

                price_val = cust_tx[cust_tx["Product"] == prod]["Price"].values[0]
                unit_price = int(round(price_val))
                final_price = int(round(price_val * qty))

                label = r["Offer"]
                pct = int(label.split("(")[1].replace("%)", "").replace("%", "")) if "%" in label else 0

                discount = int((final_price * pct) / 100)
                after_discount = final_price - discount

                invoice_rows.append({
                    "Product": prod,
                    "Quantity": qty,
                    "UnitPrice(₹)": unit_price,
                    "FinalPrice(₹)": final_price,
                    "Offer": label,
                    "DiscountAmount(₹)": discount,
                    "AfterDiscount(₹)": after_discount,
                    "Bought Dates": r["Bought Dates"]
                })

            invoice_df = pd.DataFrame(invoice_rows)

            st.subheader("💰 Invoice (₹ integer only)")
            st.dataframe(invoice_df)

            subtotal = invoice_df["FinalPrice(₹)"].sum()
            total_discount = invoice_df["DiscountAmount(₹)"].sum()
            grand_total = invoice_df["AfterDiscount(₹)"].sum()

            st.write(f"**Subtotal:** ₹ {subtotal}")
            st.write(f"**Total Discount:** ₹ {total_discount}")
            st.write(f"**Final Bill:** ₹ {grand_total}")

            csv_bytes = invoice_df.to_csv(index=False).encode("utf-8")
            st.download_button("⬇️ Download Invoice CSV", data=csv_bytes, file_name=f"invoice_{cust_key}.csv")

else:
    st.info("Upload a file to get started!")
